experiment = {
  loopScore: [],
  minNumPoint: 10,
  minConvexScore: 0.7,
  chosenData: [],
  plotSize: [100,100],
  blankSize: [20,20],
  data: [],
  lowerRadius: 0.1,
  upperRadius: 0.4,
  row: 10,
  col: 10,
  myData: [],
  nBin: 40,
  bin: [],
};
